# ENV CONFIG

defaults: &DEFAULTS
  APP_NAME: ''
  ALLOWED_TREND: ''

  SESSION_KEY: ''
  SESSION_SECRET: ''

  GOOGLE_ANALYTICS_TRACKING_CODE: ''

  TWITTER_CONSUMER_KEY: 'xsrw61YDMWXc6EFdQrKOa3qub'
  TWITTER_CONSUMER_SECRET: 'RqMB1sgSlINUjWYGtx8RItuR3DdFX9axkMykjVl5ErhxhVwCBj'
  TWITTER_ACCESS_TOKEN: '1325581308026892288-YO7meaCyX11qW84y2vvceMgYcdyV27'
  TWITTER_ACCESS_TOKEN_SECRET: 'RiEeH27s5mcx6oL3IhShkac95X6wLYv8BpmNtRWbn7VXF'

  REDIS_HOST: ''
  REDIS_PORT: ''

development:
  <<: *DEFAULTS
  APP_DOMAIN: ''

test:
  <<: *DEFAULTS
  APP_DOMAIN: ''

production:
  <<: *DEFAULTS
  APP_DOMAIN: ''
